version: '3.8'

services:
  web:
    image: my-web-app
    build: .
    ports:
      - "5001:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=messagesdb;Username=postgres;Password=123

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: messagesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
